Lesson 07
StarNembus/geekshop pull request #8
Opened 2021-10-27 15:03 UTC by StarNembus

При попытке создать категории в собственной админке в названии выходит кортеж из категорий.
Считаю, что ошибка при создании класса в forms, но не уверена.
Подскажите, пожалуйста, ошибка в forms или в созданном файле html

2021-11-07 16:46 UTC, Vokler requested changes

2021-11-07 16:46 UTC, Vokler commented on admins/views.py
> +    category = ProductCategory.objects.all(),
Запятая в конце не нужна.

Так же назовите переменную во множественном числе `categories`, так как вы берете иммено список ктаегорий (много)

2021-11-07 16:46 UTC, Vokler commented on admins/views.py
> +        'category': category,
Здесь тоже не забудьте отредактировать на `categories `

2021-11-07 16:46 UTC, Vokler commented on admins/templates/admins/admin_products_category.html
> +                                {% for category in category %}
И соответсвенно здесь отредактировать

2021-11-09 16:52 UTC, StarNembus commented
Исправила, убрала запятую и заменила category на  categories в части с админкой

2021-11-09 16:52 UTC, StarNembus commented
https://github.com/StarNembus/geekshop/pull/11

2021-11-11 12:08 UTC, merged